apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudbank-config
  namespace: cloudbank

data:

  APP_ENV: "production"

  LOG_LEVEL: "INFO"

  AUTH_SERVICE_URL: "http://auth-service:5000"

  ACCOUNT_SERVICE_URL: "http://account-service:5001"

  TRANSACTION_SERVICE_URL: "http://transaction-service:5002"

  LOAN_SERVICE_URL: "http://loan-service:5003"

  NOTIFICATION_SERVICE_URL: "http://notification-service:5004"

  API_GATEWAY_URL: "http://api-gateway:8080"

  REACT_APP_API_URL: "http://api-gateway:8080"
