apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service
  namespace: cloudbank
  labels:
    app: notification-service
    tier: backend

spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service
        tier: backend

    spec:
      containers:
      - name: notification-service

        image: shobha722/cloudbank-notificationsvc:v2 

        imagePullPolicy: Always

        ports:
        - containerPort: 5004

        envFrom:
        - configMapRef:
            name: cloudbank-config
        - secretRef:
            name: cloudbank-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 15
          periodSeconds: 5
