apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: cloudbank

type: Opaque

stringData:

  POSTGRES_USER: postgres

  POSTGRES_PASSWORD: CloudBank123

  POSTGRES_DB: cloudbank
