apiVersion: v1
kind: Secret

metadata:
  name: cloudbank-secret
  namespace: cloudbank

type: Opaque

stringData:

  JWT_SECRET: "CloudBank@123"

  DB_USERNAME: "postgres"

  DB_PASSWORD: "postgres"

  DB_HOST: "postgres"

  DB_NAME: "cloudbank"
