apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: cloudbank

  labels:
    app: frontend
    tier: frontend

spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
        tier: frontend

    spec:
      containers:

      - name: frontend

        image: shobha722/cloudbank-frontend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: cloudbank-config

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
