apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: cloudbank

  labels:
    app: auth-service
    tier: backend

spec:
  replicas: 2

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service
        tier: backend

    spec:

      containers:

      - name: auth-service

        image: shobha722/cloudbank-authservice:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: cloudbank-config

        - secretRef:
            name: cloudbank-secret

        resources:

          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5

        readinessProbe:

          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
