apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: cloudbank

spec:

  selector:
    app: auth-service

  ports:

  - port: 5000
    targetPort: 5000
    protocol: TCP

  type: ClusterIP
