apiVersion: v1
kind: Service

metadata:
  name: loan-service
  namespace: cloudbank

spec:
  selector:
    app: loan-service

  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP

  type: ClusterIP
